services:
  docs:
    container_name: docs
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile
    ports:
      - 3000:3000
    networks:
      - app_network
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - 3001:3001
    networks:
      - app_network

networks:
  app_network:
    external: true
